### ISSUE TITLE
Update chat_with_video with new models

### ISSUE THREAD

**Issue by movchan74** [mobiusml/aana_chat_with_video#3]
- New visual captioning model
- Whisper Turbo model
- other updates, if any

- speed test

**Comment by HRashidi** [comment]
Speed:
for processing 1000 images:
Blip: 68 seconds (0.068 for each image)
qwen2-2b: 501 seconds (0.501 for each image)

**Comment by appoose** [comment]
We need to investigate the speed. The current qwen speed seems to be too low.

**Comment by HRashidi** [comment]
The data for blip
max_ongoing_requests=500 and batch_size=500
1076.3250040096232 token/secs
0.03344714641571045 per image
====
max_ongoing_requests=500 and batch_size=1
139.1819998132871 token/secs
0.25865 per image
===
max_ongoing_requests=1000 and batch_size=2
286.45805220138624 token/secs
0.1256728506088257 per image

Using built in batch of vllm requests
514.784160764785 (tokens/sec)
0.21983970880508422 (per image)
